# Generated by Django 5.2.6 on 2025-09-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio_files/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
