# Generated by Django 5.2.6 on 2025-09-05 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_playlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'verbose_name': 'Playlist', 'verbose_name_plural': 'Playlists'},
        ),
    ]
