---
# Ansible: Install and configure Filebeat to ship SOC and IR logs to Elasticsearch
# Usage examples:
#   ansible-playbook elasticsearch_logstash_kibana/playbooks/elk_setup_beats.yml -i inventories/dev/hosts.yml --become \
#     -e 'ES_URL=https://es.example.com:9200 ES_API_KEY=****'
#   ansible-playbook elasticsearch_logstash_kibana/playbooks/elk_setup_beats.yml -i inventories/dev/hosts.yml --become \
#     -e 'ES_URL=https://es.example.com:9200 ES_USER=elastic ES_PASS=****'

- name: Setup Filebeat
  hosts: all
  become: true
  gather_facts: true

  vars:
    ES_URL: "{{ ES_URL | default('', true) }}"
    ES_API_KEY: "{{ ES_API_KEY | default('', true) }}"
    ES_USER: "{{ ES_USER | default('', true) }}"
    ES_PASS: "{{ ES_PASS | default('', true) }}"

    filebeat_version: "8.x"
    filebeat_conf_path: "/etc/filebeat/filebeat.yml"

  pre_tasks:
    - name: Validate ES connectivity variables provided
      assert:
        that:
          - ES_URL | length > 0
          - (ES_API_KEY | length > 0) or ((ES_USER | length > 0) and (ES_PASS | length > 0))
        fail_msg: "Provide ES_URL and either ES_API_KEY or ES_USER/ES_PASS via -e or env vars."

  tasks:
    - name: Install Filebeat (Debian/Ubuntu)
      apt:
        name: filebeat
        update_cache: yes
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install Filebeat (RHEL/CentOS/Rocky)
      yum:
        name: filebeat
        state: present
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Ensure Filebeat service enabled
      service:
        name: filebeat
        enabled: true

    - name: Template Filebeat config
      template:
        src: "{{ playbook_dir }}/../filebeat/filebeat.yml.j2"
        dest: "{{ filebeat_conf_path }}"
        owner: root
        group: root
        mode: "0644"
      notify: restart filebeat

    - name: Test Filebeat config
      shell: filebeat test config -c {{ filebeat_conf_path }}
      register: fb_test
      changed_when: false

    - name: Print Filebeat config test result
      debug:
        var: fb_test.stdout

    - name: Run Filebeat test output
      shell: filebeat test output -c {{ filebeat_conf_path }}
      register: fb_out
      changed_when: false
      failed_when: false

    - name: Show Filebeat output test result
      debug:
        var: fb_out.stdout

    - name: Ensure Filebeat started
      service:
        name: filebeat
        state: started

  handlers:
    - name: restart filebeat
      service:
        name: filebeat
        state: restarted
